version: "3.7"
services:
  client:
    build: client/
      context: . 
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      networks:
       - yolo_app

  backend:
    build: build/
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      -yolo_app

mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - /yolo_vol
    
volumes: 
  yolo_vol:

networks:
 yolo_app:
  driver: bridge
