version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
      depends_on:
      - mongo
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
  volumes: 
        yolo_vol:
      
  networks:
      yolo_app:
      driver: bridge